services:
  php:
    build: ./php
    container_name: php7-4-8
    ports:
      - "8086:80"
    volumes:
      - ./work:/var/www/html
    depends_on:
      - db
  db:
    build: ./mysql
    container_name: mysql-8
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: form-contents
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
volumes:
  db-data: